#!/usr/bin/env bash
# Installs Nginx

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install nginx -y
ufw allow 'Nignx HTTP'
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location = / {
        echo "Hello World!";
    }
}
EOF

nginx -s reload
