#!/usr/bin/env bash
# Installs Nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
