#!/usr/bin/env bash
# inatall nginx in web-02

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R ubuntu /var/www/html
sudo chmod -R 755 /var/www/html
sudo sed -i "/server_name _;/a\        add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx reload
