#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
for ((i = 1; i <= 10; i++))
do
    if [ ${i} == 10 ]
    then
    echo "Hi"
    fi
    echo "Best School"
done
